# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ec2ssh < Formula
  desc "ec2ssh is a tool that can easily ssh login to AWS EC2."
  homepage "https://github.com/tomozo6/ec2ssh"
  version "0.0.5"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomozo6/ec2ssh/releases/download/v0.0.5/ec2ssh_Darwin_x86_64.tar.gz"
      sha256 "f87e242ebe147037068a520228d063f2fb99cd3bd19c68f1fa475745e8bfc7b3"
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomozo6/ec2ssh/releases/download/v0.0.5/ec2ssh_Darwin_arm64.tar.gz"
      sha256 "89f50cd3a6086390dc8b7f72c2cb3253c5e07311defc9090e2a0154b87967bc9"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tomozo6/ec2ssh/releases/download/v0.0.5/ec2ssh_Linux_x86_64.tar.gz"
      sha256 "50f8085985d72124bab2f380f237eeb8d1796534b5451b134c6364a991811c28"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomozo6/ec2ssh/releases/download/v0.0.5/ec2ssh_Linux_arm64.tar.gz"
      sha256 "d8477521917a667fc2ecb3ab0afb6035e72234e035db90ae0c11a3d5b3375ff4"
    end
  end

  def install
    bin.install "ec2ssh"
  end

  test do
    system "#{bin}/ec2ssh -h"
  end
end
