# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dokan < Formula
  desc "dokan is a CLI tool to easily realize PortForwarding using SSMSessionManager of AWS."
  homepage "https://github.com/tomozo6/dokan"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomozo6/dokan/releases/download/v0.0.1/dokan_Darwin_x86_64.tar.gz"
      sha256 "aeac500fb4faa4b50a94e8f63282d16439e3f0bcad7f91af7845545f9ae7f9f1"

      define_method(:install) do
        bin.install "dokan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomozo6/dokan/releases/download/v0.0.1/dokan_Darwin_arm64.tar.gz"
      sha256 "3daa9c1a35b2d1cfdea33b80b106946277c9aca9551308b091e38ccac9bbf6f8"

      define_method(:install) do
        bin.install "dokan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomozo6/dokan/releases/download/v0.0.1/dokan_Linux_x86_64.tar.gz"
      sha256 "d4aa12e678f862c5fbc2b275ade37784b96c3f26d4e5a4bf1f2e23064599b47f"
      define_method(:install) do
        bin.install "dokan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomozo6/dokan/releases/download/v0.0.1/dokan_Linux_arm64.tar.gz"
      sha256 "3eab3370a7baabb260c283884f1d14d57dcbdf1dad100bae5107e01ec7340038"
      define_method(:install) do
        bin.install "dokan"
      end
    end
  end
end
