# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Getoken < Formula
  desc "getoken is a Go CLI to fetch Firebase Identity Toolkit ID tokens."
  homepage "https://github.com/tomozo6/getoken"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomozo6/getoken/releases/download/v0.0.0/getoken_Darwin_x86_64.tar.gz"
      sha256 "974bbed2cd8ce7d0752f320d545c270073a633995e4c72ca5b50bf874f067de2"

      define_method(:install) do
        bin.install "getoken"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomozo6/getoken/releases/download/v0.0.0/getoken_Darwin_arm64.tar.gz"
      sha256 "3cd8e18267e80f7ff6a838ee843d537ee3df33bc1e936c6b6f931d7f5a8a07a1"

      define_method(:install) do
        bin.install "getoken"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomozo6/getoken/releases/download/v0.0.0/getoken_Linux_x86_64.tar.gz"
      sha256 "31a21537b1f3ea6847320bb31e39dac54b63ac9268e2368ff6193eec0f71647e"
      define_method(:install) do
        bin.install "getoken"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomozo6/getoken/releases/download/v0.0.0/getoken_Linux_arm64.tar.gz"
      sha256 "531f81ff861c0c08837532532f0c0dda80e6cfc04526e575ddbf0c955b437939"
      define_method(:install) do
        bin.install "getoken"
      end
    end
  end
end
