# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moray < Formula
  desc "moray is a CLI tool to easily realize PortForwarding using SSMSessionManager of AWS."
  homepage "https://github.com/tomozo6/moray"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomozo6/moray/releases/download/v0.0.3/moray_Darwin_x86_64.tar.gz"
      sha256 "a60dfb8a92b3073674d80317de67292ce6cbae0902bb85fae9b652347fd925f3"

      def install
        bin.install "moray"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomozo6/moray/releases/download/v0.0.3/moray_Darwin_arm64.tar.gz"
      sha256 "9e4227c8d9ee48bc65bcbcf8e2df27effcf6871a127ae3c095c68555264d5949"

      def install
        bin.install "moray"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomozo6/moray/releases/download/v0.0.3/moray_Linux_arm64.tar.gz"
      sha256 "a6a33274542471b5423726b5453234571d6e02b2a8cbc3b7e1c6bee09c45f3e1"

      def install
        bin.install "moray"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tomozo6/moray/releases/download/v0.0.3/moray_Linux_x86_64.tar.gz"
      sha256 "937a599f052d003a15c86e8dac6a664759779b3b586dafa0922eeb287f3463a0"

      def install
        bin.install "moray"
      end
    end
  end
end
