# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moray < Formula
  desc "moray is a CLI tool to easily realize PortForwarding using SSMSessionManager of AWS."
  homepage "https://github.com/tomozo6/moray"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomozo6/moray/releases/download/v0.0.7/moray_Darwin_x86_64.tar.gz"
      sha256 "b30145f4ccaeba6267b24d0eff5dd454826271314f33cba28db06f09be0a326a"

      define_method(:install) do
        bin.install "moray"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomozo6/moray/releases/download/v0.0.7/moray_Darwin_arm64.tar.gz"
      sha256 "3baadab50347a5fedb7393f48b80b387bc81bb02c25385021aa08c7a1e6c1e3a"

      define_method(:install) do
        bin.install "moray"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomozo6/moray/releases/download/v0.0.7/moray_Linux_x86_64.tar.gz"
      sha256 "0a743e15f7f41e939d0714532b3ac5b2baec2c7c717aaec8d2402900e3720b6e"
      define_method(:install) do
        bin.install "moray"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomozo6/moray/releases/download/v0.0.7/moray_Linux_arm64.tar.gz"
      sha256 "047ac2fc6599140769433ef84dc74de3ecb6fcfdf698a9b74af837d806c85a77"
      define_method(:install) do
        bin.install "moray"
      end
    end
  end
end
