# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tapir < Formula
  desc "tapir is a tool that can efficiently enable and disable for AWS CloudWatchAlarm Actions."
  homepage "https://github.com/tomozo6/tapir"
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/tomozo6/tapir/releases/download/v0.1.3/tapir_Darwin_x86_64.tar.gz"
      sha256 "69583f4043b016dcd78d3e94b79028d0dd9248e992bdbcf5540a64dce3d3e862"

      def install
        bin.install "tapir"
      end
    end
    on_arm do
      url "https://github.com/tomozo6/tapir/releases/download/v0.1.3/tapir_Darwin_arm64.tar.gz"
      sha256 "c7fdc0fba133433c101e5ed2207a5c7e72cb1b6e1e5b8feb6fe0e4054af66be6"

      def install
        bin.install "tapir"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tomozo6/tapir/releases/download/v0.1.3/tapir_Linux_x86_64.tar.gz"
        sha256 "4c0af7870a12920aefa434e73f5b5bfb4d6562f99f9b9063e10ff96fd0c8959b"

        def install
          bin.install "tapir"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tomozo6/tapir/releases/download/v0.1.3/tapir_Linux_arm64.tar.gz"
        sha256 "bbf870fffd6c8aa08c128b6f66f9d0069cdf6a1387c4c9e20b855e44880aff6d"

        def install
          bin.install "tapir"
        end
      end
    end
  end
end
