# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tapir < Formula
  desc "tapir is a tool that can efficiently enable and disable for AWS CloudWatchAlarm Actions."
  homepage "https://github.com/tomozo6/tapir"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomozo6/tapir/releases/download/v0.1.4/tapir_Darwin_x86_64.tar.gz"
      sha256 "ad21627dcc200100000a7e67842ffa15f3bd346a64776f74e9ac045e64c1f8f3"

      def install
        bin.install "tapir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomozo6/tapir/releases/download/v0.1.4/tapir_Darwin_arm64.tar.gz"
      sha256 "e08ecdf319358c2b2720f7fab9084b74073402c56ef80f99d59ca122415c4a87"

      def install
        bin.install "tapir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tomozo6/tapir/releases/download/v0.1.4/tapir_Linux_x86_64.tar.gz"
        sha256 "5a691a56aed05c727c8faf775193cad4d715e2f9dd621c58515762dc53d7e331"

        def install
          bin.install "tapir"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tomozo6/tapir/releases/download/v0.1.4/tapir_Linux_arm64.tar.gz"
        sha256 "2dec1a01b634de5051468f7e524272e2afb04682337cb2f7a99f87b11a7a13ff"

        def install
          bin.install "tapir"
        end
      end
    end
  end
end
