# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfcmp < Formula
  desc "tfcmp is a Go CLI to compare Terraform code differences across environment directories."
  homepage "https://github.com/tomozo6/tfcmp"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tomozo6/tfcmp/releases/download/v0.0.0/tfcmp_Darwin_x86_64.tar.gz"
      sha256 "06eee4d5567039dca65b2be4e268b8b59291f142556857bb6510fda7def88667"

      define_method(:install) do
        bin.install "tfcmp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tomozo6/tfcmp/releases/download/v0.0.0/tfcmp_Darwin_arm64.tar.gz"
      sha256 "64fea96593554ea8a250005a4305c745e17b4d2d4f106cb809eec7bbf2ed3ac9"

      define_method(:install) do
        bin.install "tfcmp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomozo6/tfcmp/releases/download/v0.0.0/tfcmp_Linux_x86_64.tar.gz"
      sha256 "66c3388c1e5cda48acc72c1374cbb8ae0f8da4b18521c06eecc9c42fb5abc97a"
      define_method(:install) do
        bin.install "tfcmp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tomozo6/tfcmp/releases/download/v0.0.0/tfcmp_Linux_arm64.tar.gz"
      sha256 "9593fab26aeaded809b879dcea1186d2eeb70cd20c34b26963ba857bde134641"
      define_method(:install) do
        bin.install "tfcmp"
      end
    end
  end
end
